receivers:
  zipkin:

exporters:
  otlp/2:
    endpoint: data-prepper:21890
    insecure: true
  logging:

service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [logging, otlp/2]
