receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp/2:
    endpoint: data-prepper:21890
    insecure: true
  logging:
  prometheus:
    endpoint: "otel-collector:8889"
    send_timestamps: true
    metric_expiration: 180m

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/2]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]